### ISSUE TITLE
GPL Source Request for Moto G7 Power (ocean) - (PPO29.71-34, PPO29.80-14, PPO29.114-30)

### ISSUE THREAD

**Issue by no-identd** [MotorolaMobilityLLC/kernel-msm#231]
Please provide the source code for the following tags:

PPO29.71-34
PPO29.80-14
PPO29.114-30

Thanks.

**Comment by ghost** [comment]
@charleseb Hi there. In the past you helped the community get kernel sources for another Motorola device, could you help us get sources for ocean as well please? XDA developers will appreciate it!

**Comment by holyangel** [comment]
Could we possibly get source with the extra modules already included and build-able please?  

Anyone should be able to sync the release you post and build it and everything just work. With the last ocean source release touchscreen and some other things don't work and converting the extra modules zip you released is a giant pain when building the kernel outside of rom source.

**Comment by no-identd** [comment]
+1 to what @holyangel said. Also cf. #201. Cc @chenyt9 @awheeler-mmi.

…and given the rather very slow handling of source releases by Motorola (not just for this device, but in general), I figure I might as well also cc @bkuhn.

**Comment by charleseb** [comment]
Hi all,

I'm starting the process to push these tags.

Thanks,
Charles

**Comment by awheeler-mmi** [comment]
@holyangel do you mean motorola-kernel-modules? That project is separate here at Motorola, so we release it separate on Github, as well, so that y'all get the commit history.  Many of our kernel drivers are outside the kernel tree due to Android's Project Treble requirements.  We could potentially drop the release as a single zipfile, much like other manufacturers, but at the cost of the commit history.

**Comment by holyangel** [comment]
@awheeler-mmi yes that is the project I was referring to.. but no I wouldn't need a separate zip of them. I do appreciate you guys keeping the commit history. I was just hoping they could be included inside the kernel source on a release, so we don't have to do a bunch of manual editing to build them with the kernel in one go, stand-alone instead of in rom source/separate. If it can't be done that's fine though.

**Comment by awheeler-mmi** [comment]
@holyangel Got it.  That could make the entire package more easily buildable, and easier for us to produce the build instructions.  We'll look into it.

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPO29.114-30

**Comment by no-identd** [comment]
Thanks, one down, two to go! Or rather, three, as by now I have one more request for this device, namely, for:

PPO29.114-134

**Comment by charleseb** [comment]
Hi @no-identd,

This version (PPO29.114-134) is in our pipeline. It will be released in two weeks.

Could you confirm about PPO29.71-34 and PPO29.80-14, please? Looks like these mentioned versions are not official releases. 

Thanks,
Charles
