### ISSUE TITLE
Please release Moto G 5G aka Moto One 5G Ace (kiev) Kernel Source

### ISSUE THREAD

**Issue by pandayashas-github** [MotorolaMobilityLLC/kernel-msm#332]
Please release the kernel source for Moto G 5G aka Moto One 5G Ace (kiev). It's high time.

**Comment by Hasaber8** [comment]
https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-QZK30.Q4-40-62
already released , please close the issue.

**Comment by Hasaber8** [comment]
Still waiting on those Device trees for 4.19 xD @awheeler-mmi

**Comment by awheeler-mmi** [comment]
Sorry for the delay.  We are trying to catch up since our main OSS engineer, Charles is no longer on the team.  As an initial experiment with pushing DTS files, I just pushed up **MMI-QZK30.Q4-40-62* in these new gits: 

    - kernel-devicetree
    - kernel-camera-devicetree
    - kernel-display-devicetree

I believe these are all our DTS files.  Let me know if we are missing any.  

Our plan is to add the automation to our regular open-source releases, but it will take us some time to get the kinks worked out.

**Comment by Jleeblanch** [comment]
@awheeler-mmi 
You are the man! Thank you xD

**Comment by Hasaber8** [comment]
> Sorry for the delay. We are trying to catch up since our main OSS engineer, Charles is no longer on the team. As an initial experiment with pushing DTS files, I just pushed up *_MMI-QZK30.Q4-40-62_ in these new gits:
> 
> ```
> - kernel-devicetree
> - kernel-camera-devicetree
> - kernel-display-devicetree
> ```
> 
> I believe these are all our DTS files. Let me know if we are missing any.
> 
> Our plan is to add the automation to our regular open-source releases, but it will take us some time to get the kinks worked out.

Thank you very much @awheeler-mmi

**Comment by mbissaromoto** [comment]
Closing the issue. If those 3 repos listed by Andrew are not enough, please reopen this issue.
