### ISSUE TITLE
Titan kernel source?

### ISSUE THREAD

**Issue by rabih** [MotorolaMobilityLLC/kernel-msm#4]
Any reason for the super long delay? 3 Weeks is a bit much.

**Comment by akshay4** [comment]
just release it already moto move it . :+1:

**Comment by tags07** [comment]
Working on it. Should be up later this week or early next week. Also working on posting sources for the Moto X 2nd Gen

**Comment by nadlabak** [comment]
@tags07 I'm still waiting for the xt925 Razr HD 4.4.2 firmware kernel source release. I received the xt925 4.4.2 OTA on September 3rd. That's already quite a long time ago... It's probably the same source as used for the last xt907/xt926 OTA (183.46.15), for which source I'm looking forward as well.
Do you have any info about when it will be published? Thanks in advance.

**Comment by savoca** [comment]
Hey Moto, here's a quick guide on pushing to github - http://youtu.be/JxcxWoN9OYQ took me <2 minutes. Perhaps it can help cut your time down by up to a month.

**Comment by dhacker29** [comment]
Guys, not only is this unproductive but very unprofessional. You want OEM's to take community development serious, then you whine, cry, and berate them. Have some patience and courteously make your requests. It goes a lot farther.

**Comment by savoca** [comment]
What's unprofessional is their lack of compliance with GPL. There's literally no reason the source needs to be delayed as long as it is. They're using git, gerrit, and a private repo - they can easily submit to GitHub or even upload in a package in minutes. CM has they're official OPO releases public and available before the OTA is even released. I don't care what platform they use to submit their source code, I just want them to submit it.

We shouldn't have to get them to 'take community development serious'. They chose to use Linux/MSM as their platform, they shouldn't choose when they get to follow it's rules.

**Comment by tags07** [comment]
We have pushed the following releases this year:
Public Name   Release Tag      Android Version
Moto G           MMI-KXB21.14-L1.57 4.4.4
Moto X          MMI-KXA21.12-L1.28  4.4.4
Moto-G LTE  MMI-KXB21.14-L1.45  4.4.4
Moto E          MMI-KXC21.5-40  4.4.4
Moto E          MMI-KXC21.5-34  4.4.3
Droid Ultra SU2-3.3                 4.4.
Moto X          MMI-KXA21.12-L1.26  4.4.4
Moto G          MMI-KXB21.14-L1.40  4.4.4
Moto G          MM-KXB21.14-L1.32   4.4.3
Moto X          MM-KXA21.12-L1.22   4.4.3
Moto X          MM-KXA20.16-1.38            4.4.2
RAZR-M          MM-183.46.10.XT907          4.4.2
Moto E          MMI-KXC20.82-16 4.4.2
Moto X         MM-KXA20.16-1.32 4.4.2
Moto X         MM-KXA20.16-1.25 4.4.2
Moto G GPE  KOT49H.M004_5   4.4.2

This also includes all commits to releases prior to those listed above since we are posting all the commits leading up to the above releases....including releases we have not shipped on any product.

We are currently working on posting sources for titan, X+1 and any other recent releases for other products.  

@savoca, thanks for the entertaining video :)  I don't think we have a problem with that. There are many other factors such as:
a. Its better to wait a few more days to post the most recent release we plan to ship, instead of posting every other week. Mostly to manage our engineering resources, many of who also work day and night to release our development software.
b. Our current priority last month or so was to make Nexus 6 and Android L happen. Unfortunately some of our resources had to be pulled off to work on higher priority issues.
c. I dont like pushing our entire branch blindly. I ask my team to check if its just a matter of pushing a few commits instead of duplicating commits by posting entire branch for all products. This takes some time as well.
d. We also need to scrub for internal-use keywords and other stuff we don't want leaked via logs and comments.
e. We operate at a global scale with several carriers and sku variants. Most of them use common software. We have to coordinate with multiple teams to make sure we don't post duplicate stuff on github.

Trust me, all this take up time and its to better manage the releases. We have a tight process to flag any release we need to post, so be assured that all the sources will be posted in the due course.

@nadlabak: I think RAZR-M   MM-183.46.10.XT907  4.4.2 also applied to RAZR HD. They used the same kernel source. If you can post the System Version and Build Number here, I can look up.

Again, I apologize for any inconvenience caused with the delays..rest assured we are diligently working on posting them.

**Comment by savoca** [comment]
@tags07 Perhaps you could take a little constructive criticism in that case, as those reasons - although valid - seem like mere excuses to be honest.
a. "Its better to wait a few more days to post the most recent release we plan to ship, instead of posting every other week" - So every other week plus a few more days? If you need to manage engineering resources perhaps you need to assign or hire someone to manage your version control. It hasn't been 2 weeks and some extra days, it's been over a month.
b. Again, assign/hire someone to manage version control - your reasons d/e seem to imply that version control is quite the task.
c. Look into interactive rebasing on duplicate commits. Or if you're working with different branches for all variants of a product internally, then the final product you create for github will probably let you know when there's an already-existing commit anyway. 
d. An easy solution here is to write out your commit names/messages as if they were going to be presented to the public (which they are), and any internal talk can go in gerrit comments - those will not transfer over to git.
e. You're releasing one branch with all variants of a model within it. If you have to coordinate with multiple teams does that mean you have internal branches for each variant of a product? As long as those branches aren't being used for final release then you should refer to 'b'. Otherwise you should just be posting those branches as well and stop trying to unify them if they aren't even the final builds. scripts/setlocalversion can tell...

**Comment by tags07** [comment]
@savoca.. Dude, we are looking for a person of your callibre, want to join?

**Comment by motorolamobility** [comment]
+1. with good music taste too.

**Comment by savoca** [comment]
I'd be insane not to say yes. So sure.

**Comment by nadlabak** [comment]
@tags07 System version: 180.46.117.XT925.CEE-Retail.en.EU
Build number: KDA20.117

As RAZR-M MM-183.46.10.XT907 4.4.2 came before the futex patch against CVE-2014-3153, I can easily tell that the kitkat-mr1-rel-razrm branch here certainly doesn't reflect the code used in 4.4.2 build for xt925, nor in 183.46.15 builds for xt907 and xt926.

Btw., I'm really grateful that you're releasing with git history, it's priceless!

**Comment by xboxfanj** [comment]
Motorola is one of the only (along with OnePlus/CM) OEMs who releases source with a full history of not only their commits, but also upstream Linux and CAF and gives us commit messages that actually explain what each individual commit does.  Obviously, as a company, they have other processes to go through before they can release source that independent developers simply don't know about.  Be patient; we know that their code will be organized much better than other OEMs, so it is well worth the wait.  

Thank you, Gopi, Chris, and co for assuring that your source code releases are as high of quality as your products.

**Comment by tags07** [comment]
@xboxfanj Thank you for understanding. We can take a little bit of gratitude once in a while..doesn't hurt ;-)

**Comment by rknize** [comment]
The HEAD of kitkat-mr1-rel-razrm looks correct to me for the 2012
8960 products. 

Russ

**Comment by nadlabak** [comment]
@rknize Hi Russ,
both 180.46.117.XT925.CEE-Retail.en.EU (KDA20.117) and 183.46.15XT907.Verizon.en.US (KDA20.62-15.1) were built on Jul 29 2014 and definitely contain https://github.com/MotorolaMobilityLLC/kernel-msm/commit/da7d2fecc17642b3ed7f6cb48c4670eaddd35be7 
which is not present in kitkat-mr1-rel-razrm:
https://github.com/MotorolaMobilityLLC/kernel-msm/commits/kitkat-mr1-rel-razrm/kernel/futex.c

I'm not sure if there were also some other changes to msm-kernel or vendor-qcom-opensource-wlan-prima made for those builds.
That's why I ask for the sources used for those builds to be published.

Thanks, Pavel.

**Comment by nadlabak** [comment]
@tags07 @rknize Could you please confirm that the updated kernel source for msm8960 2012 products reflecting the 183.46.15 build will be published?

The thing is that a lot of 2012 msm8960 devices suffer from a speaker popping noise happening at the beginning of playback since the 4.4.2 update.

Unlocked bootloader users are asking for a rebuilt boot.img with this fix:
https://github.com/CyanogenMod/android_kernel_motorola_msm8960-common/commit/1212f2e043341016cacd6b0d93435380750bd78e

And I hesitate to build it for them from the current kitkat-mr1-rel-razrm branch as it's obviously missing the security patches present in 183.46.15 build - I don't want to make the users' devices vulnerable by missing any other possibly present security commits apart from the obvious https://github.com/MotorolaMobilityLLC/kernel-msm/commit/da7d2fecc17642b3ed7f6cb48c4670eaddd35be7.
Therefore I'm waiting for the updated 2012 msm8960 device source to be released...

Thanks in advance.

**Comment by tags07** [comment]
fyi.. We just posted Moto X Gen2 kernel sources:
Branch: kitkat-4.4.4-release-victara
TAG: MMI-KXE21.187-47

Moto G Gen2 is next..

**Comment by xboxfanj** [comment]
Thank you, @tags07

**Comment by Mohdsultan** [comment]
@tag07 we are waiting for Moto G Gen2 source from like 3 months now.I hope that you are gonna release it after the lollipop update tho and please do it asap,I know that I shouldn't ask a dev for an ETA but my mind just blew up lol.... 
I hope you do it when you satisfied that it should be OK for the devs... Thank you for the great work..

**Comment by tags07** [comment]
We posted it on Monday ;-)

**Comment by tags07** [comment]
Folks we had posted Moto G Gen 2 sources earlier this week. Sorry was too busy to update. 
Enjoy the Halloween treat!!!
More releases coming.. Including recovery images for Moto Pure and Developer Edition units

Branch: kitkat-4.4.4-release-titan
TAG: MMI-KXB21.85-24

**Comment by tags07** [comment]
Anyone care about factory recovery images for Moto X Pure Edition? Go get 'em here: https://motorola-global-portal.custhelp.com/app/standalone/bootloader/recovery-images

![screen shot 2014-11-11 at 2 20 46 pm](https://cloud.githubusercontent.com/assets/1172863/5001718/c9559be8-69ad-11e4-8211-47e57e4856de.png)

**Comment by simar7** [comment]
Sweet thanks for the update @tags07

**Comment by tags07** [comment]
if you didnt notice.. also posted VZW Moto X 4.4.4 & Droid Maxx 4.4.4 ...Enjoy!!!

**Comment by tags07** [comment]
btw, We need to fix the general  instructions to flash on the portal. We are no longer packaging an XML file. Experienced developers should have figured out that they could just follow the fastboot instructions to flash the device.
For others, here's the instruction:
1. Make sure you have a Moto Pure Edition or a Developer Edition device.
2. Make sure you download the corresponding recovery image from the above portal.
3. To flash, put the phone in fastboot mode: Power OFF...then Power ON+Volume Down .Alternatively, you can reboot into fastboot mode if you have adb... adb reboot bootloader
4. Next flash the images using fastboot:

$ fastboot flash partition gpt.bin
$ fastboot flash motoboot motoboot.img
$ fastboot reboot-bootloader
$ fastboot flash logo logo.bin
$ fastboot flash boot boot.img
$ fastboot flash recovery recovery.img
$ fastboot flash system system.img
$ fastboot flash modem NON-HLOS.bin
$ fastboot erase modemst1 
$ fastboot erase modemst2 
$ fastboot flash fsg fsg.mbn
$ fastboot reboot

Thats it... fastboot executables are included in the package for Windows, Mac and Unix/Linux﻿

**Comment by brainwave** [comment]
Thanks a ton folks at moto! :D Love the way you guys are contributing by being open about everything. I bought a moto g out of sheer respect for the whole thing.

Could you please tell me where I can your android L 'source' under development? Is it not released yet? I was hoping to get the sources, compile, and help a bit by posting/fixing bugs.

Is this possible?

**Comment by pirpi** [comment]
Even I have downloaded kernel-msm-MMI-KXB21.85-24.tar.gz for moto G 2014. Then I have build that kernel after adding usb serial driver. But size is coming lesser than required. Anyhow I managed to run the newly created boot.img. But now my sound is not working. No sound at all from the device. It is showing following error when I check with dmesg.

" failed to instantiate card msm8226-tapan9302-snd-card : -22 " and " failed to init SLIMBUS_0_RX : -22 "

Could you please help me with this?

Thanks 
pirpi

**Comment by tags07** [comment]
Sources for Moto G, Moto E and Moto G(2nd Gen) are all posted on branch: lollipop—5.0.2-release and TAG : MMI-LXB22.46-28

Sources for Moto X(2nd Gen) is posted on branch: lollipop-5.0.2-release-victara
TAG: MMI-LXE22.46-25
