### ISSUE TITLE
Kernel Source for T1TGNS33.60-114-5 (genevn)

### ISSUE THREAD

**Issue by damnthefall** [MotorolaMobilityLLC/kernel-msm#604]
### Build ID

T1TGNS33.60-114-5

**Comment by chenyt9** [comment]
@damnthefall ，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TGNS33.60-114-5

**Comment by damnthefall** [comment]
Is there any chance we could get the techpacks and everything else required to fully build this release? Along with some build instructions? Thank you in advance

**Comment by vindicatorr** [comment]
I'm wondering the same.

It looks like things are moving towards using `Bazel` to build (noted by the `build.config*` files), but it doesn't look possible to run bazel in there without a workspace.

Looking at https://github.com/MotorolaMobilityLLC/kernel-common, I DO see the workspace as `BUILD.bazel`, but there is no tag for this build id there.

You can't simply `source build.config.msm.parrot` to set up the environment because `/common/build.config.common: No such file or directory`. There is no `common` folder, and the config is in the root of the repo.

It sounds like it's WIP, but the wild thing is the last commits for those `build.config*` is in terms of YEARS!

There's also https://github.com/MotorolaMobilityLLC/kernel-build-kernel which looks to relate to bazel, but that is all out of whack as well.

And for trying to build this manually, you get `'/mnt/disks/build-disk/src/android/common-android12-5.10-2023-07/out/android12-5.10/common/abi_symbollist.raw' whitelist file not found` set for `CONFIG_UNUSED_KSYMS_WHITELIST`, maybe associated with `ABI_DEFINITION` in `build.config.msm.gki`.

**Comment by asbraga-motorola** [comment]
For techpacks, you may look for the desired tag in the repos https://github.com/MotorolaMobilityLLC/...-techpack-...
