### ISSUE TITLE
Moto G4/G4 Plus - NPJ25.93-11 Kernel Sources

### ISSUE THREAD

**Issue by Vachounet** [MotorolaMobilityLLC/kernel-msm#98]
Now it's started rolling out, could you provide the corresponding sources ?

@charleseb

**Comment by flar2** [comment]
+1

**Comment by nikitsharma15** [comment]
+1

**Comment by rahulsnair** [comment]
+2 @charleseb

**Comment by Profileman** [comment]
+1

**Comment by magdeoz** [comment]
+1

**Comment by luk1337** [comment]
-1

**Comment by luca020400** [comment]
-2
You can stop now. Moto will do its work and upload the code.

**Comment by gyuu-neves** [comment]
+1

**Comment by charleseb** [comment]
Hi all,
I've started the process to release this version. It will be available in a few days.

Thanks,
Charles

**Comment by rutwik2499** [comment]
+1

**Comment by Imwaycloud** [comment]
One month and source is not ready ...

**Comment by rahulsnair** [comment]
@charleseb  it been one month after your "few days"  It feels really sad that we need to keep reminding about the source request where you should have already published the source without request. I also wonder how you managed to release the kernel source for griffin within a week after the issue has been opened. Is motorola releasing kernel source based on price tag?

**Comment by rabih** [comment]
Most of you seem to be forgetting the fact that most of Motorola's development team is gone now...
I'm fairly surprised the development team at Motorola still bothers replying to these toxic mobs. 

Why not read up on issues #1, #4, #62 and #86? You simply ask once, and wait.

And to touch off on @rahulsnair 's price-point comment, wouldn't the force be the first to get the kernel released with that logic? A lot of you are being very unprofessional with comments like this.

If you want it quick, what's stopping them from releasing the kernel with 0 git history? I strongly prefer moderately slow releases with actual history instead of guessing what revision and changes the kernel has had.

“Patience is bitter, but its fruit is sweet.” 
― Aristotle

The release is most likely right around the corner...

**Comment by charleseb** [comment]
Hi all,
MMI-NPJ25.93-11 released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPJ25.93-11
